"""Proba table

Revision ID: 26a0e9b4ec18
Revises: b857e3e16921
Create Date: 2025-12-12 22:07:27.958132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.fields.unix_timestamp import UnixTimestampType


# revision identifiers, used by Alembic.
revision: str = '26a0e9b4ec18'
down_revision: Union[str, None] = 'b857e3e16921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', UnixTimestampType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proba')
    # ### end Alembic commands ###
