"""Add user_actions table for audit logging

Revision ID: 94cef3eb6eae
Revises: 001
Create Date: 2025-12-06 10:16:36.979693

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "94cef3eb6eae"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "user_id",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "username",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "user_roles",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "action_type",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column(
            "resource",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column(
            "ip_address",
            sqlmodel.sql.sqltypes.AutoString(length=45),
            nullable=True,
        ),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "request_id",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column(
            "request_data",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_action",
        "user_actions",
        ["user_id", "action_type"],
        unique=False,
    )
    op.create_index(
        "idx_user_timestamp",
        "user_actions",
        ["user_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_actions_action_type"),
        "user_actions",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_actions_outcome"),
        "user_actions",
        ["outcome"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_actions_request_id"),
        "user_actions",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_actions_timestamp"),
        "user_actions",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_actions_user_id"),
        "user_actions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_actions_username"),
        "user_actions",
        ["username"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_actions_username"), table_name="user_actions")
    op.drop_index(op.f("ix_user_actions_user_id"), table_name="user_actions")
    op.drop_index(op.f("ix_user_actions_timestamp"), table_name="user_actions")
    op.drop_index(
        op.f("ix_user_actions_request_id"), table_name="user_actions"
    )
    op.drop_index(op.f("ix_user_actions_outcome"), table_name="user_actions")
    op.drop_index(
        op.f("ix_user_actions_action_type"), table_name="user_actions"
    )
    op.drop_index("idx_user_timestamp", table_name="user_actions")
    op.drop_index("idx_user_action", table_name="user_actions")
    op.drop_table("user_actions")
    # ### end Alembic commands ###
