# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: websocket.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'websocket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwebsocket.proto\x12\twebsocket\"L\n\x07Request\x12\x0e\n\x06pkg_id\x18\x01 \x01(\x05\x12\x0e\n\x06req_id\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x11\n\tdata_json\x18\x04 \x01(\t\"u\n\x08Response\x12\x0e\n\x06pkg_id\x18\x01 \x01(\x05\x12\x0e\n\x06req_id\x18\x02 \x01(\t\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x12\x11\n\tdata_json\x18\x04 \x01(\t\x12!\n\x04meta\x18\x05 \x01(\x0b\x32\x13.websocket.Metadata\">\n\tBroadcast\x12\x0e\n\x06pkg_id\x18\x01 \x01(\x05\x12\x0e\n\x06req_id\x18\x02 \x01(\t\x12\x11\n\tdata_json\x18\x03 \x01(\t\"H\n\x08Metadata\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08per_page\x18\x02 \x01(\x05\x12\r\n\x05total\x18\x03 \x01(\x05\x12\r\n\x05pages\x18\x04 \x01(\x05\"H\n\x10PaginatedRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08per_page\x18\x02 \x01(\x05\x12\x14\n\x0c\x66ilters_json\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'websocket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=30
  _globals['_REQUEST']._serialized_end=106
  _globals['_RESPONSE']._serialized_start=108
  _globals['_RESPONSE']._serialized_end=225
  _globals['_BROADCAST']._serialized_start=227
  _globals['_BROADCAST']._serialized_end=289
  _globals['_METADATA']._serialized_start=291
  _globals['_METADATA']._serialized_end=363
  _globals['_PAGINATEDREQUEST']._serialized_start=365
  _globals['_PAGINATEDREQUEST']._serialized_end=437
# @@protoc_insertion_point(module_scope)
